/**
 * This file was auto-generated by openapi-typescript (via scripts/generate-api-types.mjs).
 * Do not make direct changes to the file. 生成文件,禁止手改。
 */

export type JsonValueInput = string | number | boolean | JsonValueInput[] | {
    [key: string]: JsonValueInput;
} | null;
export type JsonValueOutput = string | number | boolean | JsonValueOutput[] | {
    [key: string]: JsonValueOutput;
} | null;
export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action Apply */
        post: operations["action_apply_api_actions_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action Reconcile */
        post: operations["action_reconcile_api_actions_reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action Retry */
        post: operations["action_retry_api_actions_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action Sync */
        post: operations["action_sync_api_actions_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        /** Post Config */
        post: operations["post_config_api_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Config */
        post: operations["validate_config_api_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/raw/{source}/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Raw */
        get: operations["data_raw_api_data_raw__source___table__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/mcp-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Debug Mcp Call */
        post: operations["debug_mcp_call_api_debug_mcp_call_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/raw-table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Raw Table */
        get: operations["debug_raw_table_api_debug_raw_table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gateway/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gateway Proposals */
        post: operations["gateway_proposals_api_gateway_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Logs */
        get: operations["get_logs_api_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Objects */
        get: operations["objects_api_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Object Rows */
        get: operations["object_rows_api_objects__object__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline
         * @description 真实管道状态:固定 7 节点 + 折叠总体状态(观测口径见 observability)。
         *
         *     服务探测与数据健康分开:MCP/ingest 进程健康不覆盖数据 stale。
         */
        get: operations["pipeline_api_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quarantine */
        get: operations["quarantine_api_quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Services */
        get: operations["services_api_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Setup
         * @description Auth: skipped only while needs_setup=true (first-time bootstrap). After configuration, Bearer is required when D2A_CONSOLE_TOKEN is set.
         */
        post: operations["run_setup_api_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Setup Status
         * @description Auth: skipped only while needs_setup=true (first-time bootstrap). After configuration, Bearer is required when D2A_CONSOLE_TOKEN is set.
         */
        get: operations["setup_status_api_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Templates View */
        get: operations["templates_view_api_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config Page */
        get: operations["config_page_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Page */
        get: operations["debug_page_debug_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logs Page */
        get: operations["logs_page_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V0 */
        get: operations["v0_v0_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionBody */
        ActionBody: {
            /**
             * Deep
             * @default false
             */
            deep: boolean;
            /** Object */
            object?: string | null;
            /**
             * Source
             * @default digiwin_e10
             */
            source: string;
        };
        /** ActionExecutionResult */
        ActionExecutionResult: {
            /** Executed */
            executed: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ApplyActionResult */
        ApplyActionResult: {
            /** Aborted */
            aborted: string[];
            /** Executed */
            executed: boolean;
            /** Results */
            results: components["schemas"]["ObjectApplyResultModel"][];
        };
        /** AuditRecord */
        AuditRecord: {
            /** Action */
            action: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Rows */
            rows?: number | null;
            /** Source */
            source: string;
            /** Sql */
            sql: string;
            /**
             * Ts
             * @description legacy local ISO text from SQLite; offset/timezone not guaranteed in M1
             */
            ts: string;
        };
        /** BindingSummary */
        BindingSummary: {
            /** Disabled */
            disabled: number;
            /** Draft */
            draft: number;
            /** Verified */
            verified: number;
        };
        /** ConfigPatch */
        ConfigPatch: {
            /** Landing */
            landing?: string | null;
            /** Templates */
            templates?: string | null;
        };
        /** ConfigSaveResponse */
        ConfigSaveResponse: {
            /** Errors */
            errors?: components["schemas"]["FieldError"][];
            /** Ok */
            ok: boolean;
            /**
             * Restart Required
             * @default true
             */
            restart_required: boolean | null;
        };
        /** ConfigViewResponse */
        ConfigViewResponse: {
            /**
             * Landing
             * @default
             */
            landing: string;
            /** Needs Setup */
            needs_setup: boolean;
            /**
             * Templates
             * @default
             */
            templates: string;
        };
        /**
         * CountNote
         * @description 数量口径说明:名称、口径、数据来源。
         */
        CountNote: {
            /** Name */
            name: string;
            /** Semantics */
            semantics: string;
            /** Source */
            source: string;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HttpError
         * @description HTTPException-style error body: detail is always a string.
         */
        HttpError: {
            /** Detail */
            detail: string;
        };
        /**
         * JsonValue
         * @description Recursive JSON value with an explicit anyOf schema for OpenAPI/TS.
         *
         *     Do not use pydantic.JsonValue or Any here: those emit empty `{}` schemas that
         *     become `unknown` after openapi-typescript.
         */
        "JsonValue-Input": JsonValueInput;
        /**
         * JsonValue
         * @description Recursive JSON value with an explicit anyOf schema for OpenAPI/TS.
         *
         *     Do not use pydantic.JsonValue or Any here: those emit empty `{}` schemas that
         *     become `unknown` after openapi-typescript.
         */
        "JsonValue-Output": JsonValueOutput;
        /** LogsResponse */
        LogsResponse: {
            /** Ok */
            ok: boolean;
            /**
             * Text
             * @description Log tail text; failure must keep ok=false (not empty success)
             */
            text: string;
        };
        /** McpCallBody */
        McpCallBody: {
            /** Params */
            params?: {
                [key: string]: components["schemas"]["JsonValue-Input"];
            };
            /**
             * Tool
             * @enum {string}
             */
            tool: "query_objects" | "query_metrics";
        };
        /**
         * McpToolResult
         * @description query_objects / query_metrics 白名单工具结果;结构随工具变化,用有界 JSON 对象表达。
         */
        McpToolResult: {
            [key: string]: components["schemas"]["JsonValue-Output"];
        };
        /** ObjectApplyResultModel */
        ObjectApplyResultModel: {
            /** Mapped */
            mapped: number;
            /** Object */
            object: string;
            /** Quarantined */
            quarantined: number;
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Total */
            total: number;
        };
        /** ObjectRowsPageResponse */
        ObjectRowsPageResponse: {
            /** Limit */
            limit: number;
            /** Object */
            object: string;
            /** Offset */
            offset: number;
            /** Rows */
            rows: {
                [key: string]: components["schemas"]["JsonValue-Output"];
            }[];
            /** Total */
            total: number;
        };
        /** ObjectSummary */
        ObjectSummary: {
            /** Display Name */
            display_name: string;
            /** Domain */
            domain: string | null;
            /**
             * Mapped At
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            mapped_at: string | null;
            /** Object */
            object: string;
            /** Quarantined */
            quarantined: number;
            /**
             * Rows
             * @description 尚未物化时为 null,不等于 0
             */
            rows: number | null;
            /**
             * Version
             * @description object version 属 v0.3,当前为空
             */
            version: string | null;
        };
        /**
         * OverviewAlert
         * @description 当前告警:由节点/服务/隔离/治理状态确定性聚合,非持久化实体。
         */
        OverviewAlert: {
            /**
             * Detail Path
             * @description 详情入口;目标页未实现时为 null,不生死链
             */
            detail_path: string | null;
            /**
             * Id
             * @description kind+node/source/object 组成,刷新后稳定
             */
            id: string;
            /**
             * Observed At
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            observed_at: string | null;
            /** Reason */
            reason: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** Source */
            source: string | null;
            /** Title */
            title: string;
        };
        /** OverviewObject */
        OverviewObject: {
            /** Display Name */
            display_name: string;
            /**
             * Mapped At
             * @description legacy local ISO text from SQLite; offset/timezone not guaranteed in M1
             */
            mapped_at?: string | null;
            /** Object */
            object: string;
            /** Quarantined */
            quarantined: number;
            /** Rows */
            rows?: number | null;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Actions Sync Reconcile */
            actions_sync_reconcile: boolean;
            /** Alerts */
            alerts: components["schemas"]["OverviewAlert"][];
            binding_summary: components["schemas"]["BindingSummary"];
            /** Count Notes */
            count_notes: components["schemas"]["CountNote"][];
            /**
             * Generated At
             * Format: date-time
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            generated_at: string;
            /** Landing */
            landing: string;
            /**
             * Needs Setup
             * @default false
             */
            needs_setup: boolean;
            /** Objects */
            objects: components["schemas"]["OverviewObject"][];
            /** Readonly */
            readonly: boolean;
            /**
             * Recent Runs
             * @description 最近运行;查询失败为 null(不可检测),不返回空列表冒充从未运行
             */
            recent_runs: components["schemas"]["RecentRun"][] | null;
            /** Sources */
            sources: components["schemas"]["OverviewSource"][];
            summary: components["schemas"]["OverviewSummary"];
            /**
             * Sync Trend
             * @description 24h 趋势;查询失败为 null(不可检测),不返回空列表冒充无数据
             */
            sync_trend: components["schemas"]["SyncTrendPoint"][] | null;
            versions: components["schemas"]["OverviewVersions"];
        };
        /** OverviewSource */
        OverviewSource: {
            /** Quarantined */
            quarantined: number;
            /** Source */
            source: string;
            /** State */
            state: components["schemas"]["SyncStateRow"][];
        };
        /**
         * OverviewSummary
         * @description Dashboard 摘要计数;任一聚合不可检测时为 null,不用 0 掩盖错误。
         */
        OverviewSummary: {
            /**
             * Data Updated At
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            data_updated_at: string | null;
            /**
             * Last Run At
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            last_run_at: string | null;
            /**
             * Materialized Objects
             * @description 覆盖率分子:已物化对象数
             */
            materialized_objects: number;
            /**
             * Object Rows
             * @description 已物化 obj_* 行数合计
             */
            object_rows: number | null;
            /**
             * Quarantine Pending
             * @description 未处理隔离(resolved 为空)
             */
            quarantine_pending: number | null;
            /**
             * Raw Rows
             * @description 当前配置范围内 raw 活跃行数合计
             */
            raw_rows: number | null;
            /**
             * Template Objects
             * @description 覆盖率分母:模板对象数
             */
            template_objects: number;
        };
        /**
         * OverviewVersions
         * @description 版本信息;dataset/object version 属 v0.3,当前恒为 null(显示"尚未启用")。
         */
        OverviewVersions: {
            /**
             * App
             * @description 安装包元数据版本;取不到为 null(unknown)
             */
            app: string | null;
            /**
             * Dataset
             * @description dataset version 属 v0.3,当前为 null
             */
            dataset: string | null;
            /**
             * Object
             * @description object version 属 v0.3,当前为 null
             */
            object: string | null;
            /**
             * Template
             * @description 模板 pack 结构化 version
             */
            template: string | null;
        };
        /**
         * PipelineNode
         * @description 管道单节点。status=unknown 表示后端无法检测,前端不得显示为正常。
         */
        PipelineNode: {
            /**
             * Detail Path
             * @description 详情入口;目标页未实现时为 null,不生死链
             */
            detail_path?: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /**
             * Last Failure At
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            last_failure_at: string | null;
            /**
             * Last Success At
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            last_success_at: string | null;
            /**
             * Node
             * @description 节点 ID:erp / extract / push / raw / mapping / objects / mcp
             */
            node: string;
            /**
             * Observed At
             * @description 该节点证据的观测时间;timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            observed_at?: string | null;
            /** Rows In */
            rows_in: number | null;
            /** Rows Out */
            rows_out: number | null;
            /**
             * Run Id
             * @description 正在运行/最近一次运行的 ID
             */
            run_id?: string | null;
            /**
             * Source
             * @description 节点归属数据源
             */
            source?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "unknown" | "idle" | "running" | "healthy" | "warning" | "failed" | "stale";
            /**
             * Status Reason
             * @description 状态原因(人话;截断,不含 Token/SQL/敏感行)
             * @default
             */
            status_reason: string;
            /**
             * Version
             * @description 数据或组件版本;dataset/object version 属 v0.3,当前可为空
             */
            version: string | null;
        };
        /** PipelineResponse */
        PipelineResponse: {
            /**
             * Generated At
             * Format: date-time
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            generated_at: string;
            /** Nodes */
            nodes: components["schemas"]["PipelineNode"][];
            /**
             * Overall Status
             * @description 按 failed>stale>warning>running>unknown>idle>healthy 折叠;存在 unknown 时不得为 healthy
             * @default unknown
             * @enum {string}
             */
            overall_status: "unknown" | "idle" | "running" | "healthy" | "warning" | "failed" | "stale";
        };
        /** ProposalEvidence */
        ProposalEvidence: {
            /** Claim */
            claim: string;
            query: components["schemas"]["ProposalQueryRef"];
        };
        /** ProposalEvidenceInput */
        ProposalEvidenceInput: {
            /** Claim */
            claim: string;
            /** Query Id */
            query_id: string;
        };
        /** ProposalQueryRef */
        ProposalQueryRef: {
            /**
             * At
             * Format: date-time
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            at: string;
            /** Query Id */
            query_id: string;
            /** Target */
            target: string;
            /** Tool */
            tool: string;
        };
        /**
         * ProposalRequest
         * @description 建议卡请求,语义与 MCP propose_action 一致:
         *
         *     evidence 必须引用同会话已记录查询的 meta.query_id;不得凭空生成。
         */
        ProposalRequest: {
            /** Action */
            action: string;
            /** Conclusion */
            conclusion: string;
            /** Evidence */
            evidence: components["schemas"]["ProposalEvidenceInput"][];
            /** Object */
            object: string;
        };
        /** ProposalResponse */
        ProposalResponse: {
            /** Action */
            action: string;
            /** Action Desc */
            action_desc: string;
            /**
             * At
             * Format: date-time
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            at: string;
            /** Caveats */
            caveats: string[];
            /** Conclusion */
            conclusion: string;
            /** Evidence */
            evidence: components["schemas"]["ProposalEvidence"][];
            /** Governance */
            governance: string;
            /** Object */
            object: string;
            /** Proposal Id */
            proposal_id: string;
            /** Tier */
            tier: string;
        };
        /** QuarantineRecord */
        QuarantineRecord: {
            /**
             * Created At
             * @description legacy local ISO text from SQLite; offset/timezone not guaranteed in M1
             */
            created_at: string;
            /** Id */
            id: number;
            /** Keys Json */
            keys_json?: string | null;
            /** Object */
            object: string;
            /** Reason */
            reason: string;
            /** Source */
            source: string;
        };
        /** RawDataPageResponse */
        RawDataPageResponse: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: {
                [key: string]: components["schemas"]["JsonValue-Output"];
            }[];
            /** Source */
            source: string;
            /** Table */
            table: string;
            /** Total */
            total: number;
        };
        /** RawTablePageResponse */
        RawTablePageResponse: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: {
                [key: string]: components["schemas"]["JsonValue-Output"];
            }[];
            /** Table */
            table: string;
            /** Total */
            total: number;
        };
        /** RecentRun */
        RecentRun: {
            /**
             * Finished At
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Rows */
            rows: number | null;
            /**
             * Run Type
             * @description 结构化运行类型;历史记录为 NULL(类型未知),不回填猜测
             */
            run_type: ("sync" | "apply" | "reconcile" | "ingest") | null;
            /** Source */
            source: string;
            /**
             * Started At
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            started_at: string | null;
            /** Status */
            status: string | null;
            /** Tables */
            tables: number | null;
        };
        /**
         * RequestError
         * @description 422 body: either HTTPException string detail or FastAPI validation list.
         */
        RequestError: {
            /** Detail */
            detail: string | components["schemas"]["RequestValidationErrorItem"][];
        };
        /**
         * RequestValidationErrorItem
         * @description FastAPI/Pydantic request validation error item (422).
         */
        RequestValidationErrorItem: {
            /** Loc */
            loc: (string | number)[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /** RetryActionResult */
        RetryActionResult: {
            /** Executed */
            executed: boolean;
            /** Mapped */
            mapped: number;
            /** Object */
            object: string;
            /** Quarantined */
            quarantined: number;
            /** Status */
            status: string;
            /** Total */
            total: number;
        };
        /**
         * RunDetailResponse
         * @description 统一运行模型(v0.3 起 validation 复用同一 Run/steps 结构)。
         */
        RunDetailResponse: {
            /**
             * Dataset Version
             * @description dataset version 属 v0.3,当前为空
             */
            dataset_version: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Finished At
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Source */
            source: string | null;
            /**
             * Started At
             * Format: date-time
             * @description timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "ok" | "paused" | "failed" | "aborted";
            /** Steps */
            steps: components["schemas"]["RunStep"][];
            /**
             * Type
             * @enum {string}
             */
            type: "sync" | "apply" | "reconcile" | "ingest";
        };
        /** RunStep */
        RunStep: {
            /** Error */
            error: string | null;
            /**
             * Name
             * @description 步骤对象:表名 / 对象名 / 批次 ID
             */
            name: string;
            /** Quarantined */
            quarantined: number | null;
            /** Rows In */
            rows_in: number | null;
            /** Rows Out */
            rows_out: number | null;
            /** Watermark After */
            watermark_after: string | null;
            /** Watermark Before */
            watermark_before: string | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Detail */
            detail?: string | null;
            /**
             * Finished At
             * @description legacy local ISO text from SQLite; offset/timezone not guaranteed in M1
             */
            finished_at?: string | null;
            /** Id */
            id: number;
            /** Rows */
            rows?: number | null;
            /** Source */
            source: string;
            /**
             * Started At
             * @description legacy local ISO text from SQLite; offset/timezone not guaranteed in M1
             */
            started_at: string;
            /** Status */
            status?: string | null;
            /** Tables */
            tables?: number | null;
        };
        /** ServiceProbe */
        ServiceProbe: {
            /** Method */
            method: string;
            /** Ok */
            ok: boolean;
        };
        /** ServicesStatusResponse */
        ServicesStatusResponse: {
            apply: components["schemas"]["ServiceProbe"];
            console: components["schemas"]["ServiceProbe"];
            ingest: components["schemas"]["ServiceProbe"];
            mcp: components["schemas"]["ServiceProbe"];
        };
        /**
         * SetupBody
         * @description 浏览器首次配置(替代 setup-platform.ps1)。Token 写入 secrets.env。
         */
        SetupBody: {
            /** Console Token */
            console_token: string;
            /** Ingest Token */
            ingest_token: string;
            /** Mcp Token */
            mcp_token?: string | null;
        };
        /** SetupFailureResponse */
        SetupFailureResponse: {
            /** Errors */
            errors: components["schemas"]["FieldError"][];
            /**
             * Ok
             * @constant
             */
            ok: false;
        };
        /** SetupStatusResponse */
        SetupStatusResponse: {
            /** Config Path */
            config_path?: string | null;
            /** Home */
            home?: string | null;
            /** Needs Setup */
            needs_setup: boolean;
        };
        /** SetupSuccessResponse */
        SetupSuccessResponse: {
            /**
             * Mcp Token Generated
             * @default false
             */
            mcp_token_generated: boolean;
            /** Message */
            message: string;
            /**
             * Ok
             * @constant
             */
            ok: true;
            /**
             * Restart Required
             * @default true
             */
            restart_required: boolean;
        };
        /** SyncStateRow */
        SyncStateRow: {
            /**
             * High Water
             * @description legacy local ISO text from SQLite; offset/timezone not guaranteed in M1
             */
            high_water?: string | null;
            /**
             * Last Run At
             * @description legacy local ISO text from SQLite; offset/timezone not guaranteed in M1
             */
            last_run_at?: string | null;
            /** Table Name */
            table_name: string;
            /** Watermark Col */
            watermark_col: string;
        };
        /** SyncTrendPoint */
        SyncTrendPoint: {
            /**
             * Bucket
             * Format: date-time
             * @description 趋势桶起点(小时),timezone-aware ISO 8601 (v0.2 convention); implementing milestone must convert legacy local text to an offset-bearing value
             */
            bucket: string;
            /** Rows */
            rows: number;
            /** Runs */
            runs: number;
        };
        /** TemplateBinding */
        TemplateBinding: {
            /** Field Map */
            field_map?: {
                [key: string]: string;
            };
            /** Key Map */
            key_map?: {
                [key: string]: string;
            };
            /** Notes */
            notes?: string | null;
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "verified" | "disabled";
            /** Tables */
            tables: string[];
            /** Watermark */
            watermark?: string | null;
        };
        /** TemplateObject */
        TemplateObject: {
            /** Bindings */
            bindings: components["schemas"]["TemplateBinding"][];
            /** Description */
            description?: string | null;
            /** Display Name */
            display_name: string;
            /** Domain */
            domain?: string | null;
            /** Keys */
            keys: string[];
            /** Object */
            object: string;
            /** Properties */
            properties: components["schemas"]["TemplateProperty"][];
        };
        /** TemplateProperty */
        TemplateProperty: {
            /** Desc */
            desc?: string | null;
            /** Name */
            name: string;
            /**
             * Sensitive
             * @default false
             */
            sensitive: boolean;
            /** Type */
            type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Errors */
            errors?: components["schemas"]["FieldError"][];
            /** Ok */
            ok: boolean;
            /** Restart Required */
            restart_required?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    action_apply_api_actions_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyActionResult"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_reconcile_api_actions_reconcile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionExecutionResult"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_retry_api_actions_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryActionResult"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 请求参数错误(HTTPException 字符串 detail 或 FastAPI 校验列表) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestError"];
                };
            };
        };
    };
    action_sync_api_actions_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionExecutionResult"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecord"][];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigViewResponse"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    post_config_api_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSaveResponse"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_config_api_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_raw_api_data_raw__source___table__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                source: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawDataPageResponse"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 契约桩:端点在所属里程碑实现前返回 501 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    debug_mcp_call_api_debug_mcp_call_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["McpCallBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpToolResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    debug_raw_table_api_debug_raw_table_get: {
        parameters: {
            query: {
                table: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawTablePageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gateway_proposals_api_gateway_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 请求参数错误(HTTPException 字符串 detail 或 FastAPI 校验列表) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestError"];
                };
            };
            /** @description 契约桩:端点在所属里程碑实现前返回 501 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    get_logs_api_logs_get: {
        parameters: {
            query: {
                service: string;
                lines?: number;
                level?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    objects_api_objects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectSummary"][];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 契约桩:端点在所属里程碑实现前返回 501 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    object_rows_api_objects__object__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                object: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectRowsPageResponse"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 契约桩:端点在所属里程碑实现前返回 501 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    pipeline_api_pipeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    quarantine_api_quarantine_get: {
        parameters: {
            query?: {
                object?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantineRecord"][];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 冲突/未配置/只读/熔断 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 契约桩:端点在所属里程碑实现前返回 501 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    services_api_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesStatusResponse"];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    run_setup_api_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupSuccessResponse"] | components["schemas"]["SetupFailureResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 禁止访问 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_status_api_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
            /** @description 禁止访问 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    templates_view_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateObject"][];
                };
            };
            /** @description 缺少或无效的 Bearer Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description 契约桩:端点在所属里程碑实现前返回 501 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    config_page_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    debug_page_debug_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    logs_page_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    v0_v0_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
