"""呆滞库存场景已现场核对的鼎捷 E10 表与字段。

该清单只记录 2026-07-22 提供并核对过的表名与字段名；它不是完整的
E10 数据字典，也不隐含主键、外键或业务口径。场景 SQL 只能依赖这里列出的
字段，其他关系必须在现场补充核对后才可使用。
"""

from __future__ import annotations

from typing import Final


# 表名 -> 已确认字段。空集合表示已确认表存在，但资料未给出可供 SQL 使用的字段。
VERIFIED_E10_COLUMNS: Final[dict[str, frozenset[str]]] = {
    # 库存与成本
    "INV_COST_BAL": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "ITEM_LOT_ID", "INVENTORY_QTY"}),
    "INV_COST_BAL_DETAIL": frozenset(),
    "INV_SUMMARY": frozenset({"ITEM_ID", "WAREHOUSE_ID", "PLANT_ID", "OPENING_INVENTORY_QTY", "OPENING_AMT", "ACCOUNT_YEAR", "ACCOUNT_PERIOD_SEQNO"}),
    "INV_SUMMARY_COST_DETAIL": frozenset(),
    "INV_OPENING_COST": frozenset(),
    "INV_UNIT_COST": frozenset(),
    "ITEM_WAREHOUSE_BIN": frozenset({"ITEM_ID", "WAREHOUSE_ID", "INVENTORY_QTY", "LAST_ISSUE_DATE", "LAST_RECEIPT_DATE"}),
    "ITEM_WAREHOUSE": frozenset({"ITEM_ID", "WAREHOUSE_ID", "INVENTORY_QTY", "LAST_ISSUE_DATE", "LAST_RECEIPT_DATE", "SAFE_STOCK"}),
    # 销售
    "SALES_ORDER_DOC": frozenset({"DOC_NO", "DOC_DATE", "Owner_Dept", "Owner_Emp", "CUSTOMER_ID", "ApproveStatus"}),
    "SALES_ORDER_DOC_D": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "BUSINESS_QTY", "PRICE_QTY", "PRICE"}),
    "SALES_ORDER_DOC_SD": frozenset({"BUSINESS_QTY", "PLAN_SHIP_DATE", "PLAN_DELIVERY_DATE", "DELIVERED_BUSINESS_QTY"}),
    "SALES_ORDER_DOC_INSTAL": frozenset(),
    "SALES_DELIVERY": frozenset({"DOC_NO", "DOC_DATE", "CUSTOMER_ID", "ISSUED_STATUS"}),
    "SALES_DELIVERY_D": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "BUSINESS_QTY", "ISSUED_QTY", "SOURCE_ID_RTK", "SOURCE_ID_ROid", "SALES_ORDER_DOC_ID", "WAREHOUSE_ID", "REMARK"}),
    "SALES_ISSUE": frozenset({"DOC_NO", "DOC_DATE"}),
    "SALES_ISSUE_D": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "BUSINESS_QTY", "PRICE_QTY", "INVENTORY_QTY", "RETURN_REASON_ID", "SETTLEMENT_CLOSE"}),
    "SALES_RETURN": frozenset({"DOC_NO", "DOC_DATE", "Owner_Dept", "Owner_Emp"}),
    "SALES_RETURN_D": frozenset({"ITEM_ID", "BUSINESS_QTY", "RETURN_REASON_ID"}),
    "SALES_RETURN_RECEIPT": frozenset({"DOC_NO", "DOC_DATE"}),
    "SALES_RETURN_RECEIPT_D": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "BUSINESS_QTY", "PRICE_QTY", "INVENTORY_QTY", "WAREHOUSE_ID"}),
    # 采购
    "PURCHASE_ORDER": frozenset({"DOC_NO", "DOC_DATE", "Supplier_ID", "Owner_Dept", "Owner_Emp", "ApproveStatus"}),
    "PURCHASE_ORDER_D": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "BUSINESS_QTY", "PRICE_QTY", "PRICE"}),
    "PURCHASE_ORDER_SD": frozenset({"WAREHOUSE_ID", "PLAN_ARRIVAL_DATE", "PLANT_ID", "RECEIPT_CLOSE"}),
    "PURCHASE_ORDER_SD1": frozenset({"RECEIPTED_QTY", "DEMAND_QTY", "DEMAND_DATE", "DEMAND_NO", "PURCHASED_QTY"}),
    "PURCHASE_ORDER_SSD": frozenset({"DEMAND_NO", "DEMAND_QTY", "PURCHASED_QTY", "ARRIVED_QTY", "RECEIPTED_QTY", "LOCKED_FLAG"}),
    "PO_REQ_SOURCE": frozenset({"PURCHASE_ORDER_SD1_ID", "DEMAND_NO", "DEMAND_QTY", "PURCHASED_QTY", "PURCHASE_SEQUENCE"}),
    "PURCHASE_ARRIVAL": frozenset({"DOC_NO", "DOC_DATE", "Supplier_ID", "ARRIVAL_DATE"}),
    "PURCHASE_ARRIVAL_D": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "BUSINESS_QTY", "RECEIPTED_BUSINESS_QTY", "RETURNED_BUSINESS_QTY", "MO_ID"}),
    "PURCHASE_GOODS": frozenset({"DOC_NO", "DOC_DATE"}),
    "PURCHASE_GOODS_D": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "QTY", "DILIVER_QTY", "INVENTORY_QTY"}),
    "PURCHASE_RETURN": frozenset({"DOC_NO", "DOC_DATE"}),
    "PURCHASE_RETURN_D": frozenset({"ITEM_ID", "BUSINESS_QTY"}),
    "SUPPLIER_PURCHASE": frozenset({"SUPPLIER_ID", "DEL_CLASS", "QUL_CLASS", "ABC_CLASS"}),
    "SUPPLIER_ADDRESS": frozenset({"SUPPLIER_BUSINESS_ID", "ADDRESS", "TELEPHONE", "MAIN_ORDER_ADDR", "MAIN_DELIVERY_ADDR", "MAIN_INVOICE_ADDR"}),
    "SUPPLIER_CONTACT": frozenset({"SUPPLIER_BUSINESS_ID", "CONTACT", "TELEPHONE", "MOBILE_PHONE", "EMAIL", "MAIN_ORDER_CONTACT"}),
    "ITEM_SUPPLIER": frozenset({"ITEM_BUSINESS_ID", "SUPPLIER_ID", "PRIORITY", "MAIN", "PURCHASE_RATE"}),
    # BOM、物料、ECN 与工单
    "BOM_D": frozenset({"PARENT_ITEM_ID", "SUB_ITEM_FEATURE_ID", "QTY_PER", "DENOMINATOR", "FIXED_LOSS_RATE", "DYNAMIC_LOSS_RATE", "EFFECTIVE_DATE", "EXPRITY_DATE", "ALTERNATIVE_REPLACE", "ISSUE_OVERRUN_RATE", "ISSUE_SHORTAGE_RATE", "ITEM_TYPE"}),
    "BOM_PRODUCT": frozenset({"ITEM_ID", "PRODUCT_RATE", "PRODUCT_TYPE"}),
    "BOM_SD": frozenset({"QUANTITY", "SCRAP_RATIO", "SCRAP_QUANTITY"}),
    "BOM_MANUAL_CONFIG": frozenset(), "BOM_MANUAL_CONFIG_D": frozenset(),
    "BOM_RULE": frozenset({"ITEM_ID"}), "BOM_RULE_D": frozenset({"TYPE", "EXCEPT_ITEM", "FORMULA"}),
    "ITEM_FEATURE": frozenset({"ITEM_FEATURE_ID", "ITEM_BUSINESS_ID", "ITEM_FEATURE_CODE", "ITEM_DESC", "ITEM_SPECIFICATION", "DRAWING_NO"}),
    "ITEM_PLANT": frozenset({"ITEM_ID", "ITEM_BUSINESS_ID", "ORDER_PLANT_ID", "SAFE_STOCK", "YIELD_RATE", "ABC_CLASS", "Owner_Dept", "Owner_Emp"}),
    "ITEM_PURCHASE": frozenset({"ITEM_ID", "MINIMUM_ORDER_QUANTITY", "ORDER_MULTIPLE", "FIXED_LEAD_TIME_P", "DYNAMIC_LEAD_TIME_P"}),
    "ITEM_SALES": frozenset({"ITEM_ID", "ITEM_BUSINESS_ID", "SLS_UNIT_ID", "SLS_PRICE_UNIT_ID", "DELIVERY_PLANT_ID", "Owner_Dept", "Owner_Emp"}),
    "ITEM_LOT": frozenset({"ITEM_ID", "LOT_CODE", "EFFECTIVE_DATE", "INEFFECTIVE_DATE", "LAST_ISSUE_DATE"}),
    "ITEM_MAPPING": frozenset(), "ITEM_MAPPING_D": frozenset(),
    "ECN": frozenset({"DOC_NO", "DOC_DATE", "Owner_Dept", "Owner_Emp", "REASON_DESC", "CONTENT", "REASON_ID"}),
    "ECN_D": frozenset({"PARENT_ITEM_ID", "ORIGINAL_PARENT_ITEM_ID", "CHANGE_TYPE", "VERSION_TIMES"}),
    "ECN_SD": frozenset({"SUB_ITEM_FEATURE_ID", "ORIGINAL_SUB_ITEM_FEATURE_ID", "CHANGE_TYPE", "HANDLE", "QTY_PER", "EFFECTIVE_DATE", "EXPIRY_DATE", "REMARK"}),
    "ECN_TASK": frozenset({"DEPARTMENT_ID", "PERSON_ID", "DESCRIPTION", "START_DATE", "PLAN_DATE", "ACTUAL_DATE"}),
    "ECN_PRODUCT": frozenset({"ITEM_ID"}), "ECN_AUTO_CONFIG": frozenset({"ITEM_ID"}),
    "ECN_AUTO_CONFIG_D": frozenset(), "ECN_FACT_TABLE": frozenset(),
    "MO": frozenset({"DOC_NO", "DOC_DATE", "ITEM_ID", "Owner_Dept", "PLAN_QTY", "COMPLETED_QTY", "PLAN_START_DATE", "PLAN_COMPLETE_DATE", "STATUS", "DEMAND_NO"}),
    "MO_D": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "REQUIRED_QTY", "ISSUED_QTY", "REPLACE_ITEM", "ITEM_TYPE"}),
    "MO_DEMAND": frozenset({"DEMAND_DOC_RTK", "DEMAND_DOC_ROid", "DEMAND_QTY", "LOCKED_FLAG"}),
    "MO_ISSUED_SETS": frozenset({"MO_ID", "ISSUE_TYPE", "REQ_ISSUED_SETS", "ISSUED_SETS"}),
    "MO_PRODUCT": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "PLAN_QTY", "REQ_QTY", "COMPLETED_QTY", "SCRAP_QTY", "MO_ID"}),
    "MO_CHANGE": frozenset({"MO_ID", "CHANGE_VERSION", "CHANGE_REASON", "CHANGE_DATE", "STATUS"}),
    "MO_CHANGE_D": frozenset({"CHANGE_TYPE", "ITEM_ID", "REPLACED_ITEM_ID", "REQUIRED_QTY", "ORIGINAL_REQUIRED_QTY"}),
    "MO_RECEIPT": frozenset({"DOC_NO", "DOC_DATE", "Owner_Dept", "Owner_Emp", "WAREHOUSE_ID"}),
    "MO_RECEIPT_D": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "ACCEPTED_QTY", "SCRAP_QTY", "MO_ID", "WAREHOUSE_ID"}),
    "MO_RECEIPT_REQUISTION": frozenset({"DOC_NO", "DOC_DATE"}),
    "MO_RECEIPT_REQUISTION_D": frozenset({"ITEM_ID", "ITEM_FEATURE_ID", "REQUEST_QTY", "RECEIPT_QTY", "ACCEPTED_QTY", "SCRAP_QTY", "MO_ID", "WAREHOUSE_ID"}),
    "MO_SPLIT": frozenset({"MO_ID", "MO_SPLIT_QTY", "NEW_PLANNED_QTY", "NEW_MO_ID", "SPLIT_SEQ", "SPLIT_DATE"}),
    "MO_DAILY_PRODUCTION_QTY": frozenset({"MO_ID", "PRODUCTION_DATE", "PRODUCTION_QTY"}),
    "MO_ROUTING_MATERIAL": frozenset({"MO_ROUTING_D_ID", "SUM_QTY", "ISSUED_QTY", "TRNSFERED_QTY"}),
    "MO_ROUTING": frozenset({"MO_ID", "ROUTING_ID"}),
}


DEAD_STOCK_M1_COLUMNS: Final = frozenset({
    "ITEM_ID", "WAREHOUSE_ID", "INVENTORY_QTY", "LAST_ISSUE_DATE", "LAST_RECEIPT_DATE",
})
