<#
.SYNOPSIS
  Generate middle-server connect.yaml and machine-level credentials (Pattern A).

.DESCRIPTION
  1. Require Administrator (for Machine env vars).
  2. Prompt for ERP password and ingest token (no echo).
  3. Write ConfigDir\connect.yaml (backup if exists).
  4. Set D2A_E10_DSN, D2A_INGEST_TOKEN, and D2A_MIDDLE_ADMIN_TOKEN at Machine scope.
  5. Validate via load_config in the venv.
  6. Print NSSM AppParameters for d2a-connector and d2a-middle-admin.

  NOTE: Script text is ASCII-only so Windows PowerShell 5.x (default encoding)
  does not mis-parse UTF-8 Chinese and fail with cascading syntax errors.

.EXAMPLE
  .\setup-middle.ps1 -PlatformIP 10.0.0.5 -ErpServer erp-host -ErpDatabase E10 -ErpUser d2a_reader
  # Named instance (omit port):
  .\setup-middle.ps1 -PlatformIP 10.0.0.5 -ErpServer 'DESKTOP-X\SQLEXPRESS' -ErpDatabase E10 -ErpUser d2a_reader
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$PlatformIP,
    [int]$PlatformPort = 8850,

    [Parameter(Mandatory)]
    [string]$ErpServer,
    # 0 = omit port (required for many named instances HOST\INSTANCE)
    [int]$ErpPort = 1433,

    [Parameter(Mandatory)]
    [string]$ErpDatabase,

    [Parameter(Mandatory)]
    [string]$ErpUser,

    [string]$AppDir       = 'C:\d2a\app',
    [string]$ConfigDir    = 'C:\d2a\config',
    [string]$DataDir      = 'C:\d2a\data',
    [string]$VenvPython   = 'C:\d2a\venv\Scripts\python.exe',
    [string]$OdbcDriver   = 'ODBC Driver 18 for SQL Server',
    [string]$SyncEvery    = '30m',
    [string]$Lookback     = '3d',
    [int]$AdminPort       = 8851,

    [string]$MiddleAdminToken,

    [switch]$SkipValidate
)

$ErrorActionPreference = 'Stop'

function Write-Step([string]$msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function New-Token {
    -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 44 | ForEach-Object { [char]$_ })
}

# --- 1. Admin check --------------------------------------------------------
$isAdmin = ([Security.Principal.WindowsPrincipal] `
        [Security.Principal.WindowsIdentity]::GetCurrent()
    ).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)
if (-not $isAdmin) {
    throw 'Run PowerShell as Administrator (Machine env vars require elevation).'
}

# --- 2. Secure prompts -----------------------------------------------------
Write-Step 'Enter credentials (input is hidden)'
$erpPwdSec = Read-Host "ERP password for user [$ErpUser]" -AsSecureString
$tokenSec  = Read-Host 'Platform ingest token (D2A_INGEST_TOKEN, same as platform)' -AsSecureString

$bstrPwd = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($erpPwdSec)
$bstrTok = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($tokenSec)
try {
    $erpPwd = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstrPwd)
    $token  = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstrTok)
}
finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstrPwd)
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstrTok)
}

if ([string]::IsNullOrWhiteSpace($erpPwd)) { throw 'ERP password must not be empty.' }
if ([string]::IsNullOrWhiteSpace($token))  { throw 'Ingest token must not be empty.' }

$adminTokenGenerated = $false
if ([string]::IsNullOrWhiteSpace($MiddleAdminToken)) {
    $MiddleAdminToken = New-Token
    $adminTokenGenerated = $true
}
if ($erpPwd -match '[;{}]') {
    Write-Warning 'Password contains ; { } — ODBC DSN may break. Prefer a simpler password or verify D2A_E10_DSN.'
}

# --- 3. Write connect.yaml -------------------------------------------------
Write-Step ("Writing config " + (Join-Path $ConfigDir 'connect.yaml'))
New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
New-Item -ItemType Directory -Force -Path $DataDir   | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $DataDir 'logs') | Out-Null

$cfgPath = Join-Path $ConfigDir 'connect.yaml'
if (Test-Path $cfgPath) {
    $bak = "$cfgPath.bak-$(Get-Date -Format yyyyMMdd-HHmmss)"
    Copy-Item $cfgPath $bak -Force
    Write-Host "  Backed up old config -> $bak"
}

$templatesDir = Join-Path $AppDir 'templates'
$landingPath  = Join-Path $DataDir 'middle.sqlite'
$sinkUrl      = "http://${PlatformIP}:${PlatformPort}"

# No reconcile_at in push mode (E6b not implemented; load_config rejects it).
$yaml = @"
# Generated by setup-middle.ps1 at $(Get-Date -Format s). Credentials live in env vars only.
templates: $templatesDir
landing: $landingPath
sources:
  digiwin_e10:
    adapter: mssql_readonly
    dsn_env: D2A_E10_DSN
    tables:
      CUSTOMER:
        mode: incremental
        watermark: LAST_MODIFIED_DATE
      CURRENCY:
        mode: full_refresh
      ITEM:
        mode: incremental
        watermark: LAST_MODIFIED_DATE
      QUOTATION:
        mode: incremental
        watermark: LAST_MODIFIED_DATE
      SALES_ORDER:
        mode: incremental
        watermark: LAST_MODIFIED_DATE
      SALES_ORDER_D:
        mode: incremental
        watermark: LAST_MODIFIED_DATE
    windows: []
    rate: { batch_size: 5000, rows_per_second: 2000 }
    lookback: $Lookback
    sync_every: $SyncEvery
    sink: { type: http, url: "$sinkUrl", token_env: D2A_INGEST_TOKEN }
"@
# utf8 in Windows PowerShell 5.x writes BOM (fine for YAML)
Set-Content -Path $cfgPath -Value $yaml -Encoding utf8

# --- 4. Machine env vars ---------------------------------------------------
Write-Step 'Setting Machine env vars (D2A_E10_DSN / D2A_INGEST_TOKEN / D2A_MIDDLE_ADMIN_TOKEN)'

# Named instance HOST\INSTANCE: do not append ,port (ODBC would mis-parse).
if (($ErpServer -match '\\') -or ($ErpPort -le 0)) {
    $serverPart = $ErpServer
}
else {
    $serverPart = "$ErpServer,$ErpPort"
}

# Build DSN with concatenation — avoid "DRIVER={$var}" parse pitfalls.
$dsn = 'DRIVER={' + $OdbcDriver + '};SERVER=' + $serverPart +
       ';UID=' + $ErpUser + ';PWD=' + $erpPwd +
       ';DATABASE=' + $ErpDatabase + ';TrustServerCertificate=yes'

[Environment]::SetEnvironmentVariable('D2A_E10_DSN', $dsn, 'Machine')
[Environment]::SetEnvironmentVariable('D2A_INGEST_TOKEN', $token, 'Machine')
[Environment]::SetEnvironmentVariable('D2A_MIDDLE_ADMIN_TOKEN', $MiddleAdminToken, 'Machine')
$env:D2A_E10_DSN = $dsn
$env:D2A_INGEST_TOKEN = $token
$env:D2A_MIDDLE_ADMIN_TOKEN = $MiddleAdminToken
Write-Host "  Set (password/tokens hidden). SERVER=$serverPart  DATABASE=$ErpDatabase  UID=$ErpUser  sink=$sinkUrl"

# --- 5. Validate -----------------------------------------------------------
if ($SkipValidate) {
    Write-Step 'Skipped config validation (-SkipValidate)'
}
elseif (Test-Path $VenvPython) {
    Write-Step 'Validating config (load_config)'
    & $VenvPython -c "from data2agent.connect.config import load_config; load_config(r'$cfgPath'); print('CONFIG OK')"
    if ($LASTEXITCODE -ne 0) { throw 'Config validation failed; see errors above.' }
}
else {
    Write-Warning "Python not found at $VenvPython; skipped validation."
}

$connectorLog = Join-Path $DataDir 'logs\d2a-connector.log'

Write-Host ''
Write-Step 'Generated tokens (save these; admin UI login needs them):'
if ($adminTokenGenerated) {
    Write-Host "  D2A_MIDDLE_ADMIN_TOKEN = $MiddleAdminToken" -ForegroundColor Yellow
}
else {
    Write-Host '  D2A_MIDDLE_ADMIN_TOKEN = (provided)'
}
Write-Host '  D2A_INGEST_TOKEN          = (hidden; must match platform)'

Write-Host ''
Write-Step 'NSSM AppParameters (see windows-deploy.md section 5.1):'
Write-Host "  d2a-connector   : -m data2agent.connect serve --config $cfgPath"
Write-Host "  d2a-middle-admin: -m data2agent.middle_admin --config $cfgPath --host 0.0.0.0 --port $AdminPort --log-path $connectorLog"
Write-Host '  NOTE: Do NOT put %D2A_MIDDLE_ADMIN_TOKEN% in AppParameters.'
Write-Host '        NSSM inherits Machine env vars; middle_admin reads D2A_MIDDLE_ADMIN_TOKEN from the process environment.'

Write-Host ''
Write-Step 'Done. Next steps:'
Write-Host '  1. Open a NEW PowerShell window (Machine env vars apply to new processes).'
Write-Host "  2. Ensure platform ingest is listening at $sinkUrl"
Write-Host '  3. Smoke test in the new window:'
Write-Host "     $VenvPython -m data2agent.connect serve --config $cfgPath --once" -ForegroundColor Yellow
Write-Host "  4. Admin UI: http://<this-host-ip>:$AdminPort (login with D2A_MIDDLE_ADMIN_TOKEN)"
Write-Host "  5. Firewall: allow inbound TCP $AdminPort from internal admin subnets only (not public)."
