<#
.SYNOPSIS
  Generate platform platform.yaml and machine-level tokens (Pattern A receive side).

.DESCRIPTION
  1. Require Administrator.
  2. Prompt for D2A_INGEST_TOKEN (must match middle server).
  3. Auto-generate D2A_MCP_TOKEN / D2A_CONSOLE_TOKEN if not provided.
  4. Write ConfigDir\platform.yaml (backup if exists).
  5. Set Machine env vars; validate with load_config.
  6. Print NSSM AppParameters for the four services.

  NOTE: ASCII-only script text for Windows PowerShell 5.x encoding safety.

.EXAMPLE
  .\setup-platform.ps1
#>
[CmdletBinding()]
param(
    [string]$AppDir       = 'C:\d2a\app',
    [string]$ConfigDir    = 'C:\d2a\config',
    [string]$DataDir      = 'C:\d2a\data',
    [string]$VenvPython   = 'C:\d2a\venv\Scripts\python.exe',
    [int]$IngestPort      = 8850,
    [int]$McpPort         = 8848,
    [int]$ConsolePort     = 8849,
    [int]$ApplyEvery      = 1800,

    [string]$McpToken,
    [string]$ConsoleToken,

    [switch]$SkipValidate
)

$ErrorActionPreference = 'Stop'

function Write-Step([string]$msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function New-Token {
    -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 44 | ForEach-Object { [char]$_ })
}

# --- 1. Admin check --------------------------------------------------------
$isAdmin = ([Security.Principal.WindowsPrincipal] `
        [Security.Principal.WindowsIdentity]::GetCurrent()
    ).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)
if (-not $isAdmin) {
    throw 'Run PowerShell as Administrator (Machine env vars require elevation).'
}

# --- 2. Tokens -------------------------------------------------------------
Write-Step 'Enter / generate tokens'
$ingestSec = Read-Host 'Platform ingest token (D2A_INGEST_TOKEN, same as middle)' -AsSecureString
$bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($ingestSec)
try {
    $ingestToken = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
}
finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
}
if ([string]::IsNullOrWhiteSpace($ingestToken)) { throw 'Ingest token must not be empty.' }

$mcpGenerated = $false
$consoleGenerated = $false
if ([string]::IsNullOrWhiteSpace($McpToken))     { $McpToken = New-Token;     $mcpGenerated = $true }
if ([string]::IsNullOrWhiteSpace($ConsoleToken)) { $ConsoleToken = New-Token; $consoleGenerated = $true }

# --- 3. Write platform.yaml ------------------------------------------------
Write-Step ("Writing config " + (Join-Path $ConfigDir 'platform.yaml'))
New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $DataDir 'logs') | Out-Null

$cfgPath = Join-Path $ConfigDir 'platform.yaml'
if (Test-Path $cfgPath) {
    $bak = "$cfgPath.bak-$(Get-Date -Format yyyyMMdd-HHmmss)"
    Copy-Item $cfgPath $bak -Force
    Write-Host "  Backed up old config -> $bak"
}

$templatesDir = Join-Path $AppDir 'templates'
$landingPath  = Join-Path $DataDir 'factory.sqlite'

$yaml = @"
# Generated by setup-platform.ps1 at $(Get-Date -Format s)
templates: $templatesDir
landing: $landingPath
sources:
  digiwin_e10:
    adapter: mssql_readonly
    dsn_env: D2A_E10_DSN_PLACEHOLDER
"@
Set-Content -Path $cfgPath -Value $yaml -Encoding utf8

# --- 4. Machine env vars ---------------------------------------------------
Write-Step 'Setting Machine env vars (D2A_INGEST_TOKEN / D2A_MCP_TOKEN / D2A_CONSOLE_TOKEN)'
[Environment]::SetEnvironmentVariable('D2A_INGEST_TOKEN', $ingestToken, 'Machine')
[Environment]::SetEnvironmentVariable('D2A_MCP_TOKEN', $McpToken, 'Machine')
[Environment]::SetEnvironmentVariable('D2A_CONSOLE_TOKEN', $ConsoleToken, 'Machine')
$env:D2A_INGEST_TOKEN = $ingestToken
$env:D2A_MCP_TOKEN = $McpToken
$env:D2A_CONSOLE_TOKEN = $ConsoleToken

# --- 5. Validate -----------------------------------------------------------
if ($SkipValidate) {
    Write-Step 'Skipped config validation (-SkipValidate)'
}
elseif (Test-Path $VenvPython) {
    Write-Step 'Validating config (load_config)'
    & $VenvPython -c "from data2agent.connect.config import load_config; load_config(r'$cfgPath'); print('CONFIG OK')"
    if ($LASTEXITCODE -ne 0) { throw 'Config validation failed; see errors above.' }
}
else {
    Write-Warning "Python not found at $VenvPython; skipped validation."
}

# --- 6. Print tokens and service args --------------------------------------
Write-Host ''
Write-Step 'Generated tokens (save these; clients need them):'
if ($mcpGenerated)     { Write-Host "  D2A_MCP_TOKEN     = $McpToken" -ForegroundColor Yellow }
else                   { Write-Host '  D2A_MCP_TOKEN     = (provided)' }
if ($consoleGenerated) { Write-Host "  D2A_CONSOLE_TOKEN = $ConsoleToken" -ForegroundColor Yellow }
else                   { Write-Host '  D2A_CONSOLE_TOKEN = (provided)' }
Write-Host '  D2A_INGEST_TOKEN  = (hidden; must match middle)'

Write-Host ''
Write-Step 'NSSM AppParameters (see windows-deploy.md section 5.2):'
Write-Host "  d2a-ingest : -m data2agent.ingest --landing $landingPath --host 0.0.0.0 --port $IngestPort"
Write-Host "  d2a-apply  : -m data2agent.connect apply --landing $landingPath --templates $templatesDir --every $ApplyEvery"
Write-Host "  d2a-mcp    : -m data2agent.mcp_server --db $landingPath --templates $templatesDir --transport http --host 0.0.0.0 --port $McpPort"
$logDir = Join-Path $DataDir 'logs'
Write-Host "  d2a-console: -m data2agent.console --config $cfgPath --host 0.0.0.0 --port $ConsolePort --log-dir $logDir"

Write-Host ''
Write-Step 'Done. Next steps:'
Write-Host '  1. Open a NEW PowerShell window before starting services.'
Write-Host "  2. Start d2a-ingest first (port $IngestPort) so middle can push."
Write-Host '  3. Then run middle serve --once; check raw_* tables on this machine.' -ForegroundColor Yellow
Write-Host "  4. Platform admin UI: http://<this-host-ip>:$ConsolePort (login with D2A_CONSOLE_TOKEN)"
Write-Host '     Legacy JSON API remains at /v0 on the same port.'
